const sko = [{
        img: 'img/sko/piruettUltra.jpg',
        pris: '1000',
        navn: 'Piruett Ultra',
        objectFit: 'contain',
    },
    {
        img: 'img/sko/classicGalosh.jpg',
        pris: '700',
        navn: 'Classic Galosh Black',
        objectFit: 'contain',
    },
    {
        img: 'img/sko/classicGaloshOrange.jpg',
        pris: '650',
        navn: 'Classic Galosh Orange',
        objectFit: 'contain',
    },
    {
        img: 'img/sko/piruettOnTheGo.jpg',
        pris: '200',
        navn: 'Piruett on the go - biltema edition',
        objectFit: 'contain',
    },
    {
        img: 'img/sko/piruettUltra.jpg',
        pris: '1000',
        navn: 'Piruett Ultra',
        objectFit: 'contain',
    },
    {
        img: 'img/sko/classicGalosh.jpg',
        pris: '700',
        navn: 'Classic Galosh Black',
        objectFit: 'contain',
    },
    {
        img: 'img/sko/classicGaloshOrange.jpg',
        pris: '650',
        navn: 'Classic Galosh Orange',
        objectFit: 'contain',
    },
    {
        img: 'img/sko/piruettUltra.jpg',
        pris: '1000',
        navn: 'Piruett Ultra',
        objectFit: 'contain',
    },
    {
        img: 'img/sko/classicGalosh.jpg',
        pris: '700',
        navn: 'Classic Galosh Black',
        objectFit: 'contain',
    },
    {
        img: 'img/sko/classicGaloshOrange.jpg',
        pris: '650',
        navn: 'Classic Galosh Orange',
        objectFit: 'contain',
    },
]